# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# ===================================================================
server:
  servlet:
    context-path: {{ BOILERPLATE_CONTEXT_PATH }}
spring:
  application:
    name: BOILERPLATE_APPLICATION_NAME
  profiles:
    active:  #spring.profiles.active#
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    #show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: {{ BOILERPLATE_DB_URL }}
    username: {{ BOILERPLATE_DB_USERNAME }}
    password: {{ BOILERPLATE_DB_PASSWORD }}
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  resources:
    add-mappings: true
  liquibase:
    change-log: classpath:config/liquibase/master.xml
  thymeleaf:
    mode: HTML
    cache: true
  mail:
    host: localhost
    port: 25
    username:
    password:
# Application properties
application:
  security:
    authentication:
      jwt:
        secret: my-secret-token-to-change-in-production
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail:
    from: boilerplate@localhost
    base-url: http://127.0.01:8080
# Properties to be exposed on the /info management endpoint
#info:
