spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
# Application properties
application:
  clientApp:
    name: 'BoilerplateApp'
  security:
    authentication:
      jwt:
        base64-secret: ZTc2MjU3YWQyOGFhY2M0NDE4YTZkNDFiMjE5Yjk5YTgxNDQ1NDliYmEwZDBlZWYwODVkNjdhNzVlZDA1ZWRkZTRjZTgxYmViNDljZjI2NmYwY2FlYjNjMWE3MmY2Y2I4OWJlMGVjZTZmZjlkMGEyMjNmZjYzY2UwNGI1ZmNjZjY=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  credentials:
    user: kiabi
    pass: kiabi123
management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers